import type { AIProviderSettings, ModelRouteDecision, ModelTaskLane } from "./model-router.ts";
import { selectModelForTask } from "./model-router.ts";

export type GenerateInput = {
  settings: AIProviderSettings;
  lane: ModelTaskLane;
  system: string;
  user: string;
  temperature?: number;
  maxTokens?: number;
};

export type GenerateOutput = {
  route: ModelRouteDecision;
  text: string;
  finishReason: string;
  inputTokens: number;
  outputTokens: number;
  latencyMs: number;
  localFallback: boolean;
};

type ChatMessage = {
  role: "system" | "user" | "assistant";
  content: string;
};

function openAIModelDisallowsTemperature(model: string) {
  const normalized = model.toLowerCase();
  return /^o\d/.test(normalized) || normalized.startsWith("gpt-5");
}

function isUnsupportedTemperatureError(error: unknown) {
  const message = error instanceof Error ? error.message.toLowerCase() : String(error).toLowerCase();
  return message.includes("temperature") && (message.includes("unsupported") || message.includes("not supported"));
}

function estimateTokens(text: string) {
  return Math.max(1, Math.ceil(text.length / 4));
}

function localGenerate(input: GenerateInput, route: ModelRouteDecision, latencyMs: number): GenerateOutput {
  const elapsedMs = Math.max(latencyMs, 35);
  const skillLabel =
    input.system.match(/governed enterprise Skill "([^"]+)"/)?.[1] ??
    input.system.match(/You are the ([^.]+)\./)?.[1] ??
    "configured Skill";
  const contractId = input.system.match(/Contract ID:\s*([^\n]+)/)?.[1]?.trim();
  const text = [
    `${skillLabel} completed a governed local Harness run.`,
    contractId ? `Prompt contract ${contractId} was applied before model routing.` : "A governed prompt contract was applied before model routing.",
    "The response was generated by the deterministic local runtime because no server-side provider is configured or available for this route.",
    "Grounding, tool-use, approval, and output-safety claims remain bounded by the Harness trace.",
    "Attach provider secrets in the server environment to enable live model calls.",
  ].join(" ");

  return {
    route,
    text,
    finishReason: "local_fallback",
    inputTokens: estimateTokens(`${input.system}\n${input.user}`),
    outputTokens: estimateTokens(text),
    latencyMs: elapsedMs,
    localFallback: true,
  };
}

async function postJson<T>(url: string, init: RequestInit, timeoutMs = 45000): Promise<T> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(url, { ...init, signal: controller.signal });
    const payload = await response.json().catch(() => ({}));
    if (!response.ok) {
      const message =
        typeof payload === "object" && payload && "error" in payload
          ? JSON.stringify(payload.error)
          : `${response.status} ${response.statusText}`;
      throw new Error(message);
    }
    return payload as T;
  } finally {
    clearTimeout(timeout);
  }
}

async function callOpenAICompatible(params: {
  baseUrl: string;
  apiKey: string;
  model: string;
  messages: ChatMessage[];
  temperature: number;
  maxTokens: number;
}): Promise<{ text: string; finishReason: string; inputTokens: number; outputTokens: number }> {
  const basePayload = {
      model: params.model,
      messages: params.messages,
      max_tokens: params.maxTokens,
  };
  const request = (includeTemperature: boolean) =>
    postJson<{
      choices?: { message?: { content?: string }; finish_reason?: string }[];
      usage?: { prompt_tokens?: number; completion_tokens?: number };
    }>(`${params.baseUrl.replace(/\/$/, "")}/chat/completions`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${params.apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        ...basePayload,
        ...(includeTemperature ? { temperature: params.temperature } : {}),
      }),
  });
  const includeTemperature = !openAIModelDisallowsTemperature(params.model);
  let payload: {
    choices?: { message?: { content?: string }; finish_reason?: string }[];
    usage?: { prompt_tokens?: number; completion_tokens?: number };
  };
  try {
    payload = await request(includeTemperature);
  } catch (error) {
    if (!includeTemperature || !isUnsupportedTemperatureError(error)) throw error;
    payload = await request(false);
  }

  return {
    text: payload.choices?.[0]?.message?.content ?? "",
    finishReason: payload.choices?.[0]?.finish_reason ?? "stop",
    inputTokens: payload.usage?.prompt_tokens ?? estimateTokens(params.messages.map((message) => message.content).join("\n")),
    outputTokens: payload.usage?.completion_tokens ?? estimateTokens(payload.choices?.[0]?.message?.content ?? ""),
  };
}

async function callOpenAIResponses(params: {
  baseUrl: string;
  apiKey: string;
  model: string;
  system: string;
  user: string;
  temperature: number;
  maxTokens: number;
}): Promise<{ text: string; finishReason: string; inputTokens: number; outputTokens: number }> {
  const basePayload = {
      model: params.model,
      instructions: params.system,
      input: params.user,
      max_output_tokens: params.maxTokens,
  };
  const request = (includeTemperature: boolean) =>
    postJson<{
      output_text?: string;
      status?: string;
      incomplete_details?: { reason?: string };
      usage?: { input_tokens?: number; output_tokens?: number };
      output?: {
        content?: { type?: string; text?: string }[];
      }[];
    }>(`${params.baseUrl.replace(/\/$/, "")}/responses`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${params.apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        ...basePayload,
        ...(includeTemperature ? { temperature: params.temperature } : {}),
      }),
    });
  const includeTemperature = !openAIModelDisallowsTemperature(params.model);
  let payload: {
    output_text?: string;
    status?: string;
    incomplete_details?: { reason?: string };
    usage?: { input_tokens?: number; output_tokens?: number };
    output?: {
      content?: { type?: string; text?: string }[];
    }[];
  };
  try {
    payload = await request(includeTemperature);
  } catch (error) {
    if (!includeTemperature || !isUnsupportedTemperatureError(error)) throw error;
    payload = await request(false);
  }

  const text =
    payload.output_text ??
    payload.output
      ?.flatMap((item) => item.content ?? [])
      .map((content) => content.text ?? "")
      .join("") ??
    "";

  return {
    text,
    finishReason: payload.incomplete_details?.reason ?? payload.status ?? "completed",
    inputTokens: payload.usage?.input_tokens ?? estimateTokens(`${params.system}\n${params.user}`),
    outputTokens: payload.usage?.output_tokens ?? estimateTokens(text),
  };
}

async function callAnthropic(params: {
  baseUrl: string;
  apiKey: string;
  model: string;
  system: string;
  user: string;
  temperature: number;
  maxTokens: number;
}): Promise<{ text: string; finishReason: string; inputTokens: number; outputTokens: number }> {
  const payload = await postJson<{
    content?: { type?: string; text?: string }[];
    stop_reason?: string;
    usage?: { input_tokens?: number; output_tokens?: number };
  }>(`${params.baseUrl.replace(/\/$/, "")}/v1/messages`, {
    method: "POST",
    headers: {
      "x-api-key": params.apiKey,
      "anthropic-version": "2023-06-01",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: params.model,
      system: params.system,
      messages: [{ role: "user", content: params.user }],
      temperature: params.temperature,
      max_tokens: params.maxTokens,
    }),
  });

  const text = payload.content?.find((item) => item.type === "text")?.text ?? "";

  return {
    text,
    finishReason: payload.stop_reason ?? "stop",
    inputTokens: payload.usage?.input_tokens ?? estimateTokens(`${params.system}\n${params.user}`),
    outputTokens: payload.usage?.output_tokens ?? estimateTokens(text),
  };
}

async function callGemini(params: {
  baseUrl: string;
  apiKey: string;
  model: string;
  system: string;
  user: string;
  temperature: number;
  maxTokens: number;
}): Promise<{ text: string; finishReason: string; inputTokens: number; outputTokens: number }> {
  const payload = await postJson<{
    candidates?: { content?: { parts?: { text?: string }[] }; finishReason?: string }[];
    usageMetadata?: { promptTokenCount?: number; candidatesTokenCount?: number };
  }>(
    `${params.baseUrl.replace(/\/$/, "")}/v1beta/models/${params.model}:generateContent?key=${encodeURIComponent(params.apiKey)}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        systemInstruction: { parts: [{ text: params.system }] },
        contents: [{ role: "user", parts: [{ text: params.user }] }],
        generationConfig: {
          temperature: params.temperature,
          maxOutputTokens: params.maxTokens,
        },
      }),
    },
  );

  const text = payload.candidates?.[0]?.content?.parts?.map((part) => part.text ?? "").join("") ?? "";

  return {
    text,
    finishReason: payload.candidates?.[0]?.finishReason ?? "stop",
    inputTokens: payload.usageMetadata?.promptTokenCount ?? estimateTokens(`${params.system}\n${params.user}`),
    outputTokens: payload.usageMetadata?.candidatesTokenCount ?? estimateTokens(text),
  };
}

async function callAzureOpenAI(params: {
  endpoint: string;
  apiKey: string;
  deployment: string;
  messages: ChatMessage[];
  temperature: number;
  maxTokens: number;
}): Promise<{ text: string; finishReason: string; inputTokens: number; outputTokens: number }> {
  const endpoint = params.endpoint.replace(/\/$/, "");
  const payload = await postJson<{
    choices?: { message?: { content?: string }; finish_reason?: string }[];
    usage?: { prompt_tokens?: number; completion_tokens?: number };
  }>(`${endpoint}/openai/deployments/${params.deployment}/chat/completions?api-version=2024-10-21`, {
    method: "POST",
    headers: {
      "api-key": params.apiKey,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      messages: params.messages,
      temperature: params.temperature,
      max_tokens: params.maxTokens,
    }),
  });

  return {
    text: payload.choices?.[0]?.message?.content ?? "",
    finishReason: payload.choices?.[0]?.finish_reason ?? "stop",
    inputTokens: payload.usage?.prompt_tokens ?? estimateTokens(params.messages.map((message) => message.content).join("\n")),
    outputTokens: payload.usage?.completion_tokens ?? estimateTokens(payload.choices?.[0]?.message?.content ?? ""),
  };
}

export async function generateWithModelProvider(input: GenerateInput): Promise<GenerateOutput> {
  const started = Date.now();
  const route = selectModelForTask(input.settings, input.lane);
  const temperature = input.temperature ?? 0.2;
  const maxTokens = input.maxTokens ?? 1200;
  const messages: ChatMessage[] = [
    { role: "system", content: input.system },
    { role: "user", content: input.user },
  ];

  try {
    if (route.provider === "openai") {
      const result = await callOpenAIResponses({
        baseUrl: input.settings.openaiBaseUrl,
        apiKey: input.settings.openaiKey,
        model: route.model,
        system: input.system,
        user: input.user,
        temperature,
        maxTokens,
      });
      return { route, ...result, latencyMs: Date.now() - started, localFallback: false };
    }

    if (route.provider === "anthropic") {
      const result = await callAnthropic({
        baseUrl: input.settings.anthropicBaseUrl,
        apiKey: input.settings.anthropicKey,
        model: route.model,
        system: input.system,
        user: input.user,
        temperature,
        maxTokens,
      });
      return { route, ...result, latencyMs: Date.now() - started, localFallback: false };
    }

    if (route.provider === "google") {
      const result = await callGemini({
        baseUrl: input.settings.googleBaseUrl,
        apiKey: input.settings.googleKey,
        model: route.model,
        system: input.system,
        user: input.user,
        temperature,
        maxTokens,
      });
      return { route, ...result, latencyMs: Date.now() - started, localFallback: false };
    }

    if (route.provider === "azure_openai") {
      const result = await callAzureOpenAI({
        endpoint: input.settings.azureEndpoint,
        apiKey: input.settings.azureKey,
        deployment: route.model,
        messages,
        temperature,
        maxTokens,
      });
      return { route, ...result, latencyMs: Date.now() - started, localFallback: false };
    }

    if (route.provider === "kimi") {
      const result = await callOpenAICompatible({
        baseUrl: input.settings.kimiBaseUrl,
        apiKey: input.settings.kimiKey,
        model: route.model,
        messages,
        temperature,
        maxTokens,
      });
      return { route, ...result, latencyMs: Date.now() - started, localFallback: false };
    }

    if (route.provider === "glm") {
      const result = await callOpenAICompatible({
        baseUrl: input.settings.glmBaseUrl,
        apiKey: input.settings.glmKey,
        model: route.model,
        messages,
        temperature,
        maxTokens,
      });
      return { route, ...result, latencyMs: Date.now() - started, localFallback: false };
    }

    if (route.provider === "deepseek") {
      const result = await callOpenAICompatible({
        baseUrl: input.settings.deepseekBaseUrl,
        apiKey: input.settings.deepseekKey,
        model: route.model,
        messages,
        temperature,
        maxTokens,
      });
      return { route, ...result, latencyMs: Date.now() - started, localFallback: false };
    }

    if (route.provider === "openrouter") {
      const result = await callOpenAICompatible({
        baseUrl: input.settings.openrouterBaseUrl,
        apiKey: input.settings.openrouterKey,
        model: route.model,
        messages,
        temperature,
        maxTokens,
      });
      return { route, ...result, latencyMs: Date.now() - started, localFallback: false };
    }
  } catch (error) {
    const fallbackRoute: ModelRouteDecision = {
      provider: "local",
      model: "local-enterprise-reasoner",
      modelRef: "local/local-enterprise-reasoner",
      fallbackUsed: true,
      reason: `Provider call failed: ${error instanceof Error ? error.message : "unknown error"}. Deterministic local runtime is active.`,
    };
    return localGenerate(input, fallbackRoute, Date.now() - started);
  }

  return localGenerate(input, route, Date.now() - started);
}
