/**
 * Rich, realistic demo tenant ("Northwind Group"). Loaded on demand from Admin;
 * the app still boots empty in production. Cross-references (owner ids, skill ids,
 * tool ids, context source names) are kept internally consistent so every view
 * renders populated, believable content.
 */
import {
  calculatePriorityScore,
  riskToScore,
  type AuditLog,
  type ContextSource,
  type EvalResult,
  type GovernanceReview,
  type Run,
  type Skill,
  type Tool,
  type ToolRequest,
  type UseCase,
  type User,
  type WorkSignal,
} from "../enterprise-ai-data.ts";
import type { EnterpriseWorkspace, OrganizationSettings } from "../workspace-schema.ts";

export const demoUsers: User[] = [
  { id: "u-amara", name: "Amara Okafor", email: "amara.okafor@northwind.example", title: "VP, AI Enablement", department: "IT", role: "Platform Admin" },
  { id: "u-david", name: "David Chen", email: "david.chen@northwind.example", title: "Head of HR Operations", department: "HR", role: "Skill Owner" },
  { id: "u-sofia", name: "Sofia Marino", email: "sofia.marino@northwind.example", title: "Finance Transformation Lead", department: "Finance", role: "Skill Owner" },
  { id: "u-raj", name: "Raj Patel", email: "raj.patel@northwind.example", title: "Senior Counsel", department: "Legal", role: "Skill Owner" },
  { id: "u-lena", name: "Lena Hoffmann", email: "lena.hoffmann@northwind.example", title: "Procurement Director", department: "Procurement", role: "Skill Owner" },
  { id: "u-marcus", name: "Marcus Webb", email: "marcus.webb@northwind.example", title: "IT Service Manager", department: "IT", role: "Skill Owner" },
  { id: "u-yuki", name: "Yuki Tanaka", email: "yuki.tanaka@northwind.example", title: "GRC Lead", department: "Compliance", role: "Governance Reviewer" },
  { id: "u-priya", name: "Priya Nair", email: "priya.nair@northwind.example", title: "Operations Excellence Manager", department: "Operations", role: "Skill Owner" },
];

export const demoTools: Tool[] = [
  { id: "t-workday-read", displayName: "Workday — Read Worker", description: "Read employee profile, org, and leave balances", category: "HR", actionType: "read", riskLevel: "medium", requiresApprovalByDefault: false, enabled: true, usage: 5210, lastUsed: "May 27, 2026, 9:12 AM" },
  { id: "t-servicenow-create", displayName: "ServiceNow — Create Incident", description: "Open and route IT service incidents", category: "ITSM", actionType: "create", riskLevel: "medium", requiresApprovalByDefault: true, enabled: true, usage: 4100, lastUsed: "May 28, 2026, 7:48 AM" },
  { id: "t-sap-invoice-read", displayName: "SAP — Read Invoice", description: "Retrieve invoice, PO, and vendor records", category: "Finance", actionType: "read", riskLevel: "medium", requiresApprovalByDefault: false, enabled: true, usage: 980, lastUsed: "May 27, 2026, 4:31 PM" },
  { id: "t-coupa-po", displayName: "Coupa — Create Purchase Order", description: "Draft and submit purchase orders for approval", category: "Procurement", actionType: "create", riskLevel: "high", requiresApprovalByDefault: true, enabled: true, usage: 320, lastUsed: "May 26, 2026, 1:05 PM" },
  { id: "t-docusign-send", displayName: "DocuSign — Send Envelope", description: "Send contracts for signature", category: "Legal", actionType: "execute", riskLevel: "restricted", requiresApprovalByDefault: true, enabled: false, usage: 42, lastUsed: "May 20, 2026, 10:22 AM" },
  { id: "t-slack-post", displayName: "Slack — Post Message", description: "Post updates to approved channels", category: "Collaboration", actionType: "write", riskLevel: "low", requiresApprovalByDefault: false, enabled: true, usage: 2750, lastUsed: "May 28, 2026, 8:15 AM" },
  { id: "t-confluence-read", displayName: "Confluence — Search Pages", description: "Search and retrieve internal documentation", category: "Knowledge", actionType: "read", riskLevel: "low", requiresApprovalByDefault: false, enabled: true, usage: 8900, lastUsed: "May 28, 2026, 8:02 AM" },
  { id: "t-jira-update", displayName: "Jira — Update Issue", description: "Transition and comment on engineering issues", category: "ITSM", actionType: "update", riskLevel: "medium", requiresApprovalByDefault: false, enabled: true, usage: 1640, lastUsed: "May 27, 2026, 6:40 PM" },
  { id: "t-snowflake-query", displayName: "Snowflake — Run Query", description: "Run read-only analytical queries on governed marts", category: "Data", actionType: "read", riskLevel: "medium", requiresApprovalByDefault: false, enabled: true, usage: 610, lastUsed: "May 27, 2026, 2:18 PM" },
  { id: "t-email-send", displayName: "Email — Send Message", description: "Send templated email to internal recipients", category: "Collaboration", actionType: "execute", riskLevel: "medium", requiresApprovalByDefault: true, enabled: true, usage: 430, lastUsed: "May 26, 2026, 5:55 PM" },
];

export const demoContextSources: ContextSource[] = [
  { id: "cs-hr-policies", name: "HR Policy Library", type: "Confluence Space", classification: "confidential", ownerDepartment: "HR", enabled: true, lastIndexedAt: "May 28, 2026, 6:00 AM", documentCount: 1840, skillsUsing: 1, health: "healthy" },
  { id: "cs-finance-sop", name: "Finance SOP Hub", type: "SharePoint Site", classification: "confidential", ownerDepartment: "Finance", enabled: true, lastIndexedAt: "May 28, 2026, 6:05 AM", documentCount: 920, skillsUsing: 1, health: "healthy" },
  { id: "cs-legal-contracts", name: "Contract Repository", type: "iManage", classification: "restricted", ownerDepartment: "Legal", enabled: true, lastIndexedAt: "May 25, 2026, 6:00 AM", documentCount: 12400, skillsUsing: 1, health: "attention" },
  { id: "cs-procurement-catalog", name: "Procurement Catalog", type: "Coupa Export", classification: "internal", ownerDepartment: "Procurement", enabled: true, lastIndexedAt: "May 28, 2026, 5:40 AM", documentCount: 360, skillsUsing: 0, health: "healthy" },
  { id: "cs-it-runbooks", name: "IT Runbooks", type: "Confluence Space", classification: "internal", ownerDepartment: "IT", enabled: true, lastIndexedAt: "May 28, 2026, 6:10 AM", documentCount: 540, skillsUsing: 1, health: "healthy" },
  { id: "cs-compliance-reg", name: "Regulatory Library", type: "GRC Repository", classification: "regulated", ownerDepartment: "Compliance", enabled: true, lastIndexedAt: "May 18, 2026, 6:00 AM", documentCount: 2100, skillsUsing: 0, health: "stale" },
  { id: "cs-product-kb", name: "Product Knowledge Base", type: "Zendesk Guide", classification: "internal", ownerDepartment: "Operations", enabled: true, lastIndexedAt: "May 28, 2026, 6:02 AM", documentCount: 1280, skillsUsing: 1, health: "healthy" },
];

type UseCaseSeed = Omit<UseCase, "riskScore" | "priorityScore">;

function makeUseCase(seed: UseCaseSeed): UseCase {
  const riskScore = riskToScore(seed.riskLevel);
  return {
    ...seed,
    riskScore,
    priorityScore: calculatePriorityScore({
      valueScore: seed.valueScore,
      feasibilityScore: seed.feasibilityScore,
      reuseScore: seed.reuseScore,
      urgencyScore: seed.urgencyScore,
      dataReadinessScore: seed.dataReadinessScore,
      riskScore,
    }),
  };
}

export const demoUseCases: UseCase[] = [
  makeUseCase({
    id: "uc-hr-helpdesk",
    title: "HR Policy Helpdesk Assistant",
    description: "Answer employee HR policy questions with cited, permission-aware responses.",
    department: "HR",
    requestorId: "u-david",
    ownerId: "u-david",
    businessProblem: "HR fields 6,000+ repetitive policy questions monthly, creating long wait times and inconsistent answers.",
    currentProcess: "Employees email or ticket HR; specialists manually look up policy and reply within 1-2 days.",
    desiredOutcome: "Instant, cited answers for 70% of tier-1 questions with clean escalation to humans.",
    monthlyVolume: 6200,
    avgHandlingTimeMinutes: 11,
    estimatedUsers: 14000,
    capabilityType: "Grounded Q&A",
    status: "scaled",
    riskLevel: "medium",
    valueScore: 5,
    feasibilityScore: 5,
    reuseScore: 5,
    urgencyScore: 4,
    dataReadinessScore: 4,
    expectedBenefits: ["70% deflection of tier-1 tickets", "Sub-second response time", "Consistent, cited policy answers"],
    dataSources: ["HR Policy Library", "Benefits SOPs"],
    risks: ["Outdated policy retrieval", "Over-broad benefits guidance"],
    linkedSkillId: "sk-hr-helpdesk",
    createdAt: "2026-01-12T15:00:00.000Z",
    updatedAt: "2026-05-22T16:30:00.000Z",
  }),
  makeUseCase({
    id: "uc-invoice-triage",
    title: "Invoice Exception Triage",
    description: "Classify and route invoice exceptions, drafting matched purchase orders for approval.",
    department: "Finance",
    requestorId: "u-sofia",
    ownerId: "u-sofia",
    businessProblem: "AP analysts spend ~30 minutes per exception reconciling invoices against POs and receipts.",
    currentProcess: "Analysts manually open SAP, match documents, and email approvers for non-PO spend.",
    desiredOutcome: "Auto-classified exceptions with a drafted PO and a one-click approval packet.",
    monthlyVolume: 980,
    avgHandlingTimeMinutes: 30,
    estimatedUsers: 120,
    capabilityType: "Classification + Action",
    status: "in_pilot",
    riskLevel: "medium",
    valueScore: 5,
    feasibilityScore: 4,
    reuseScore: 4,
    urgencyScore: 4,
    dataReadinessScore: 4,
    expectedBenefits: ["50% faster exception handling", "Fewer late-payment penalties", "Cleaner audit trail"],
    dataSources: ["Finance SOP Hub", "SAP Invoices"],
    risks: ["Incorrect PO match", "Duplicate payment"],
    linkedSkillId: "sk-invoice-triage",
    createdAt: "2026-02-03T14:00:00.000Z",
    updatedAt: "2026-05-26T13:10:00.000Z",
  }),
  makeUseCase({
    id: "uc-contract-review",
    title: "NDA & Contract First-Pass Review",
    description: "Flag risky clauses against the playbook and summarize redline recommendations.",
    department: "Legal",
    requestorId: "u-raj",
    ownerId: "u-raj",
    businessProblem: "Counsel reviews 400+ standard NDAs monthly, delaying deals by days.",
    currentProcess: "Lawyers read each agreement and compare against the clause playbook manually.",
    desiredOutcome: "First-pass risk flags and suggested redlines for human counsel to confirm.",
    monthlyVolume: 420,
    avgHandlingTimeMinutes: 45,
    estimatedUsers: 35,
    capabilityType: "Document Analysis",
    status: "governance_review",
    riskLevel: "high",
    valueScore: 4,
    feasibilityScore: 3,
    reuseScore: 3,
    urgencyScore: 3,
    dataReadinessScore: 3,
    expectedBenefits: ["Faster contract turnaround", "Consistent playbook enforcement", "Counsel focuses on judgment calls"],
    dataSources: ["Contract Repository"],
    risks: ["Missed material clause", "Unauthorized signature action", "Privilege/confidentiality exposure"],
    linkedSkillId: "sk-contract-review",
    createdAt: "2026-03-09T16:30:00.000Z",
    updatedAt: "2026-05-24T11:45:00.000Z",
  }),
  makeUseCase({
    id: "uc-po-assist",
    title: "Procurement Intake Assistant",
    description: "Guide requesters to the right vendor, contract, and category, drafting compliant POs.",
    department: "Procurement",
    requestorId: "u-lena",
    ownerId: "u-lena",
    businessProblem: "Off-catalog and maverick spend drives up cost and slows approvals.",
    currentProcess: "Requesters guess vendors and categories; procurement reworks most intake forms.",
    desiredOutcome: "Guided intake that proposes preferred vendors and a compliant draft PO.",
    monthlyVolume: 540,
    avgHandlingTimeMinutes: 22,
    estimatedUsers: 900,
    capabilityType: "Guided Workflow",
    status: "approved_for_pilot",
    riskLevel: "medium",
    valueScore: 4,
    feasibilityScore: 4,
    reuseScore: 4,
    urgencyScore: 3,
    dataReadinessScore: 4,
    expectedBenefits: ["Less maverick spend", "Faster cycle time", "Higher catalog adoption"],
    dataSources: ["Procurement Catalog"],
    risks: ["Wrong vendor recommendation", "Budget overrun"],
    createdAt: "2026-04-01T15:00:00.000Z",
    updatedAt: "2026-05-20T09:20:00.000Z",
  }),
  makeUseCase({
    id: "uc-it-incident",
    title: "IT Incident Auto-Triage",
    description: "Classify incoming incidents, draft remediation steps, and route to the right queue.",
    department: "IT",
    requestorId: "u-marcus",
    ownerId: "u-marcus",
    businessProblem: "Service desk mis-routes ~25% of incidents, inflating mean time to resolution.",
    currentProcess: "L1 agents manually categorize and assign tickets from free-text reports.",
    desiredOutcome: "Accurate auto-categorization with drafted first-response and routing.",
    monthlyVolume: 4100,
    avgHandlingTimeMinutes: 9,
    estimatedUsers: 14000,
    capabilityType: "Classification + Action",
    status: "measuring",
    riskLevel: "medium",
    valueScore: 5,
    feasibilityScore: 5,
    reuseScore: 4,
    urgencyScore: 4,
    dataReadinessScore: 5,
    expectedBenefits: ["25% faster MTTR", "Fewer mis-routes", "Higher CSAT"],
    dataSources: ["IT Runbooks"],
    risks: ["Mis-categorized priority incident", "Automated action on wrong asset"],
    linkedSkillId: "sk-it-incident",
    createdAt: "2026-01-28T17:00:00.000Z",
    updatedAt: "2026-05-27T18:50:00.000Z",
  }),
  makeUseCase({
    id: "uc-compliance-monitor",
    title: "Regulatory Change Monitor",
    description: "Summarize incoming regulatory updates and map them to affected internal controls.",
    department: "Compliance",
    requestorId: "u-yuki",
    ownerId: "u-yuki",
    businessProblem: "Regulatory updates are tracked manually, risking missed obligations.",
    currentProcess: "Analysts read regulator bulletins and update a control spreadsheet by hand.",
    desiredOutcome: "Drafted impact summaries linked to the affected controls for analyst review.",
    monthlyVolume: 160,
    avgHandlingTimeMinutes: 75,
    estimatedUsers: 40,
    capabilityType: "Summarization + Mapping",
    status: "scored",
    riskLevel: "restricted",
    valueScore: 4,
    feasibilityScore: 3,
    reuseScore: 3,
    urgencyScore: 4,
    dataReadinessScore: 2,
    expectedBenefits: ["No missed obligations", "Faster control updates", "Auditable change history"],
    dataSources: ["Regulatory Library"],
    risks: ["Misinterpreted regulation", "Stale regulatory index", "Incorrect control mapping"],
    createdAt: "2026-04-22T14:30:00.000Z",
    updatedAt: "2026-05-19T10:05:00.000Z",
  }),
  makeUseCase({
    id: "uc-ops-kb",
    title: "Operations Knowledge Assistant",
    description: "Answer frontline operations questions from the product knowledge base with citations.",
    department: "Operations",
    requestorId: "u-priya",
    ownerId: "u-priya",
    businessProblem: "New operations staff ramp slowly and ask repetitive process questions.",
    currentProcess: "Staff search the KB or ask team leads, interrupting experienced operators.",
    desiredOutcome: "Cited, instant answers from the approved KB with escalation when unsure.",
    monthlyVolume: 2300,
    avgHandlingTimeMinutes: 6,
    estimatedUsers: 1200,
    capabilityType: "Grounded Q&A",
    status: "in_pilot",
    riskLevel: "low",
    valueScore: 4,
    feasibilityScore: 5,
    reuseScore: 5,
    urgencyScore: 3,
    dataReadinessScore: 4,
    expectedBenefits: ["Faster onboarding", "Fewer interruptions to leads", "Consistent process answers"],
    dataSources: ["Product Knowledge Base"],
    risks: ["Outdated KB article surfaced"],
    linkedSkillId: "sk-ops-kb",
    createdAt: "2026-03-18T15:30:00.000Z",
    updatedAt: "2026-05-25T12:00:00.000Z",
  }),
];

export const demoSkills: Skill[] = [
  {
    id: "sk-hr-helpdesk",
    useCaseId: "uc-hr-helpdesk",
    name: "HR Policy Helpdesk",
    slug: "hr-policy-helpdesk",
    description: "Cited, permission-aware answers to employee HR policy questions.",
    department: "HR",
    ownerId: "u-david",
    status: "production",
    version: "2.3.0",
    riskLevel: "medium",
    autonomyTier: "tier_2_prepare_action",
    modelProvider: "anthropic",
    model: "claude-sonnet-4-6",
    temperature: 0.2,
    maxTokens: 1500,
    fallbackModel: "openai/gpt-4o-mini",
    costLimit: 500,
    systemPrompt: "You are the Northwind HR policy assistant. Answer only from approved HR sources, always cite the policy, and escalate benefits or leave determinations to a human specialist.",
    allowedTools: ["t-workday-read", "t-confluence-read"],
    blockedTools: ["t-email-send"],
    contextSources: ["HR Policy Library", "Benefits SOPs"],
    evalPassRate: 96,
    adoptionCount: 1840,
    valueDelivered: 412000,
    runs: 5210,
    updatedAt: "2026-05-22T16:30:00.000Z",
  },
  {
    id: "sk-invoice-triage",
    useCaseId: "uc-invoice-triage",
    name: "Invoice Exception Triage",
    slug: "invoice-exception-triage",
    description: "Classifies AP exceptions and drafts matched purchase orders for approval.",
    department: "Finance",
    ownerId: "u-sofia",
    status: "pilot",
    version: "1.4.0",
    riskLevel: "medium",
    autonomyTier: "tier_3_execute_bounded_action",
    modelProvider: "openai",
    model: "gpt-4o",
    temperature: 0.1,
    maxTokens: 2000,
    fallbackModel: "anthropic/claude-haiku-4-5",
    costLimit: 750,
    systemPrompt: "Classify each invoice exception, match it to the correct PO and receipt, and prepare an approval packet. Never submit payment; always require human approval for non-PO spend.",
    allowedTools: ["t-sap-invoice-read", "t-coupa-po"],
    blockedTools: ["t-email-send"],
    contextSources: ["Finance SOP Hub"],
    evalPassRate: 91,
    adoptionCount: 240,
    valueDelivered: 168000,
    runs: 980,
    updatedAt: "2026-05-26T13:10:00.000Z",
  },
  {
    id: "sk-contract-review",
    useCaseId: "uc-contract-review",
    name: "Contract First-Pass Review",
    slug: "contract-first-pass-review",
    description: "Flags risky clauses against the playbook and proposes redlines for counsel.",
    department: "Legal",
    ownerId: "u-raj",
    status: "in_review",
    version: "0.9.0",
    riskLevel: "high",
    autonomyTier: "tier_1_read_only",
    modelProvider: "anthropic",
    model: "claude-opus-4-6",
    temperature: 0.2,
    maxTokens: 3000,
    fallbackModel: "openai/gpt-4o",
    costLimit: 600,
    systemPrompt: "Compare each agreement against the Northwind clause playbook. Flag deviations and suggest redlines, but never send or execute documents. Treat all contract text as confidential and privileged.",
    allowedTools: ["t-confluence-read"],
    blockedTools: ["t-docusign-send", "t-email-send"],
    contextSources: ["Contract Repository"],
    evalPassRate: 84,
    adoptionCount: 60,
    valueDelivered: 54000,
    runs: 210,
    updatedAt: "2026-05-24T11:45:00.000Z",
  },
  {
    id: "sk-it-incident",
    useCaseId: "uc-it-incident",
    name: "IT Incident Auto-Triage",
    slug: "it-incident-auto-triage",
    description: "Categorizes incidents, drafts first response, and routes to the correct queue.",
    department: "IT",
    ownerId: "u-marcus",
    status: "production",
    version: "3.1.0",
    riskLevel: "medium",
    autonomyTier: "tier_3_execute_bounded_action",
    modelProvider: "anthropic",
    model: "claude-sonnet-4-6",
    temperature: 0.1,
    maxTokens: 1800,
    fallbackModel: "openai/gpt-4o-mini",
    costLimit: 900,
    systemPrompt: "Categorize each incident, draft a first response from the runbooks, and route to the correct assignment group. Require approval before any change action on production assets.",
    allowedTools: ["t-servicenow-create", "t-jira-update", "t-confluence-read"],
    blockedTools: [],
    contextSources: ["IT Runbooks"],
    evalPassRate: 94,
    adoptionCount: 920,
    valueDelivered: 286000,
    runs: 4100,
    updatedAt: "2026-05-27T18:50:00.000Z",
  },
  {
    id: "sk-ops-kb",
    useCaseId: "uc-ops-kb",
    name: "Operations Knowledge Assistant",
    slug: "operations-knowledge-assistant",
    description: "Cited answers to frontline operations questions from the approved KB.",
    department: "Operations",
    ownerId: "u-priya",
    status: "pilot",
    version: "1.1.0",
    riskLevel: "low",
    autonomyTier: "tier_1_read_only",
    modelProvider: "google",
    model: "gemini-2.5-flash",
    temperature: 0.3,
    maxTokens: 1200,
    fallbackModel: "anthropic/claude-haiku-4-5",
    costLimit: 300,
    systemPrompt: "Answer operations questions only from the approved product knowledge base. Always cite the article and escalate when confidence is low.",
    allowedTools: ["t-confluence-read", "t-snowflake-query"],
    blockedTools: ["t-email-send"],
    contextSources: ["Product Knowledge Base"],
    evalPassRate: 93,
    adoptionCount: 320,
    valueDelivered: 78000,
    runs: 1450,
    updatedAt: "2026-05-25T12:00:00.000Z",
  },
];

export const demoRuns: Run[] = [
  {
    id: "run-1001",
    skillId: "sk-hr-helpdesk",
    useCaseId: "uc-hr-helpdesk",
    triggeredBy: "u-david",
    status: "completed",
    riskLevel: "low",
    currentStage: "Completed",
    costUsd: 0.018,
    latencyMs: 2400,
    startedAt: "May 28, 2026, 8:02 AM",
    output: "Provided the parental leave policy with citation to HR-204 and escalated the pay-continuation question to a benefits specialist.",
    trace: [
      { label: "Permission check", status: "completed", detail: "Verified requester scope against HR policy ACL.", latencyMs: 120 },
      { label: "Context retrieval", status: "completed", detail: "Retrieved 3 cited snippets from HR Policy Library.", latencyMs: 640 },
      { label: "Model response", status: "completed", detail: "Drafted answer with citations.", latencyMs: 1480 },
      { label: "Escalation", status: "completed", detail: "Flagged benefits determination for human review.", latencyMs: 160 },
    ],
  },
  {
    id: "run-1002",
    skillId: "sk-invoice-triage",
    useCaseId: "uc-invoice-triage",
    triggeredBy: "u-sofia",
    status: "waiting_for_approval",
    riskLevel: "medium",
    currentStage: "Awaiting approval",
    costUsd: 0.041,
    latencyMs: 5200,
    startedAt: "May 28, 2026, 7:40 AM",
    output: "Classified invoice INV-88213 as a non-PO exception and drafted PO #PO-44910 for $18,400, pending approver sign-off.",
    trace: [
      { label: "Permission check", status: "completed", detail: "Confirmed AP analyst scope.", latencyMs: 110 },
      { label: "Invoice match", status: "completed", detail: "Read SAP invoice and matched vendor master.", latencyMs: 1700 },
      { label: "Draft PO", status: "completed", detail: "Prepared Coupa PO draft.", latencyMs: 2200 },
      { label: "Approval gate", status: "waiting", detail: "Held for human approval of non-PO spend.", latencyMs: 0 },
    ],
  },
  {
    id: "run-1003",
    skillId: "sk-it-incident",
    useCaseId: "uc-it-incident",
    triggeredBy: "u-marcus",
    status: "completed",
    riskLevel: "low",
    currentStage: "Completed",
    costUsd: 0.012,
    latencyMs: 1900,
    startedAt: "May 28, 2026, 7:12 AM",
    output: "Categorized incident as 'VPN connectivity', drafted first response from runbook RB-19, and routed to Network Ops.",
    trace: [
      { label: "Permission check", status: "completed", detail: "Validated service desk scope.", latencyMs: 90 },
      { label: "Classification", status: "completed", detail: "Predicted category with 0.97 confidence.", latencyMs: 540 },
      { label: "Runbook retrieval", status: "completed", detail: "Pulled remediation steps from IT Runbooks.", latencyMs: 720 },
      { label: "Route", status: "completed", detail: "Assigned to Network Ops queue.", latencyMs: 550 },
    ],
  },
  {
    id: "run-1004",
    skillId: "sk-contract-review",
    useCaseId: "uc-contract-review",
    triggeredBy: "u-raj",
    status: "blocked",
    riskLevel: "high",
    currentStage: "Blocked by policy",
    costUsd: 0.0,
    latencyMs: 300,
    startedAt: "May 27, 2026, 3:20 PM",
    output: "Run blocked: the skill requested DocuSign send, which is denied by policy for tier-1 read-only contract review.",
    trace: [
      { label: "Permission check", status: "completed", detail: "Validated counsel scope.", latencyMs: 100 },
      { label: "Tool request", status: "blocked", detail: "DocuSign send denied by autonomy tier policy.", latencyMs: 200 },
    ],
  },
  {
    id: "run-1005",
    skillId: "sk-ops-kb",
    useCaseId: "uc-ops-kb",
    triggeredBy: "u-priya",
    status: "running",
    riskLevel: "low",
    currentStage: "Generating answer",
    costUsd: 0.004,
    latencyMs: 800,
    startedAt: "May 28, 2026, 8:18 AM",
    output: "",
    trace: [
      { label: "Permission check", status: "completed", detail: "Validated operations scope.", latencyMs: 80 },
      { label: "Context retrieval", status: "completed", detail: "Retrieved 2 KB articles.", latencyMs: 420 },
      { label: "Model response", status: "running", detail: "Composing cited answer.", latencyMs: 0 },
    ],
  },
];

export const demoToolRequests: ToolRequest[] = [
  { id: "tr-1", skillId: "sk-invoice-triage", runId: "run-1002", user: "u-sofia", toolId: "t-coupa-po", reason: "Draft PO #PO-44910 for non-PO invoice exception, pending approval.", riskLevel: "high", status: "pending", requestedAt: "May 28, 2026, 7:41 AM" },
  { id: "tr-2", skillId: "sk-it-incident", runId: "run-1003", user: "u-marcus", toolId: "t-servicenow-create", reason: "Create and route incident INC-55821 to Network Ops.", riskLevel: "medium", status: "approved", requestedAt: "May 28, 2026, 7:12 AM" },
  { id: "tr-3", skillId: "sk-contract-review", runId: "run-1004", user: "u-raj", toolId: "t-docusign-send", reason: "Send NDA for signature (auto-generated).", riskLevel: "restricted", status: "blocked", requestedAt: "May 27, 2026, 3:20 PM" },
  { id: "tr-4", skillId: "sk-hr-helpdesk", runId: "run-1001", user: "u-david", toolId: "t-workday-read", reason: "Read requester leave balance to answer PTO question.", riskLevel: "medium", status: "approved", requestedAt: "May 28, 2026, 8:02 AM" },
];

export const demoAuditLogs: AuditLog[] = [
  { id: "al-1", eventType: "skill_run_completed", message: "HR Policy Helpdesk completed run run-1001 with citations.", actor: "HR Policy Helpdesk", riskLevel: "low", createdAt: "May 28, 2026, 8:02 AM" },
  { id: "al-2", eventType: "approval_requested", message: "Invoice Exception Triage requested approval for PO #PO-44910.", actor: "Invoice Exception Triage", riskLevel: "high", createdAt: "May 28, 2026, 7:41 AM" },
  { id: "al-3", eventType: "tool_denied", message: "DocuSign send denied by policy for Contract First-Pass Review.", actor: "Policy Engine", riskLevel: "high", createdAt: "May 27, 2026, 3:20 PM" },
  { id: "al-4", eventType: "skill_published", message: "IT Incident Auto-Triage v3.1.0 promoted to production.", actor: "Marcus Webb", riskLevel: "medium", createdAt: "May 27, 2026, 6:55 PM" },
  { id: "al-5", eventType: "governance_decision", message: "Invoice Exception Triage approved with conditions by GRC.", actor: "Yuki Tanaka", riskLevel: "medium", createdAt: "May 26, 2026, 2:30 PM" },
  { id: "al-6", eventType: "context_indexed", message: "Regulatory Library index is stale (10 days); refresh recommended.", actor: "Context Fabric", riskLevel: "medium", createdAt: "May 28, 2026, 6:00 AM" },
  { id: "al-7", eventType: "eval_completed", message: "Contract First-Pass Review scored 84% with 2 critical failures.", actor: "Evaluation Runner", riskLevel: "high", createdAt: "May 24, 2026, 11:40 AM" },
  { id: "al-8", eventType: "skill_run_completed", message: "IT Incident Auto-Triage routed INC-55821 to Network Ops.", actor: "IT Incident Auto-Triage", riskLevel: "low", createdAt: "May 28, 2026, 7:12 AM" },
];

export const demoGovernanceReviews: GovernanceReview[] = [
  { id: "gr-1", itemType: "use_case", itemId: "uc-contract-review", title: "NDA & Contract First-Pass Review", department: "Legal", riskLevel: "high", reviewer: "u-yuki", status: "in_review", dueDate: "May 30, 2026", blockers: ["Grounding eval below 90% threshold", "Confirm DocuSign remains hard-blocked"] },
  { id: "gr-2", itemType: "skill", itemId: "sk-invoice-triage", title: "Invoice Exception Triage", department: "Finance", riskLevel: "medium", reviewer: "u-yuki", status: "approved_with_conditions", dueDate: "May 22, 2026", blockers: ["Mandatory human approval for non-PO spend"] },
  { id: "gr-3", itemType: "use_case", itemId: "uc-compliance-monitor", title: "Regulatory Change Monitor", department: "Compliance", riskLevel: "restricted", reviewer: "u-yuki", status: "not_submitted", dueDate: "June 6, 2026", blockers: ["Regulatory Library index is stale", "Data classification review pending"] },
  { id: "gr-4", itemType: "skill", itemId: "sk-it-incident", title: "IT Incident Auto-Triage", department: "IT", riskLevel: "medium", reviewer: "u-yuki", status: "approved", dueDate: "May 18, 2026", blockers: [] },
];

export const demoEvalResults: EvalResult[] = [
  { id: "ev-1", skillId: "sk-hr-helpdesk", suiteName: "HR Helpdesk Safety & Grounding", score: 96, passed: true, criticalFailures: 0, createdAt: "May 22, 2026, 4:10 PM" },
  { id: "ev-2", skillId: "sk-invoice-triage", suiteName: "Invoice Triage Accuracy", score: 91, passed: true, criticalFailures: 1, createdAt: "May 26, 2026, 12:50 PM" },
  { id: "ev-3", skillId: "sk-contract-review", suiteName: "Contract Review Grounding", score: 84, passed: false, criticalFailures: 2, createdAt: "May 24, 2026, 11:40 AM" },
  { id: "ev-4", skillId: "sk-it-incident", suiteName: "Incident Routing Suite", score: 94, passed: true, criticalFailures: 0, createdAt: "May 27, 2026, 6:30 PM" },
  { id: "ev-5", skillId: "sk-ops-kb", suiteName: "KB Grounding Suite", score: 93, passed: true, criticalFailures: 0, createdAt: "May 25, 2026, 11:30 AM" },
];

const standardSignalPrivacy: WorkSignal["privacy"] = {
  contentRedacted: true,
  piiRedacted: true,
  consentBasis: "aggregated",
  retentionDays: 90,
  individualScoringAllowed: false,
  rawContentStored: false,
};

export const demoWorkSignals: WorkSignal[] = [
  {
    id: "ws-hr-pto-questions",
    source: "service_now",
    eventType: "question_asked",
    department: "HR",
    process: "Employee policy self-service",
    teamId: "hr-ops-tier1",
    summary: "Aggregated ticket metadata shows repeated PTO carryover, leave eligibility, and benefits timing questions.",
    metadata: { volume: 1840, cycleTimeHours: 18, delayHours: 12, confidence: 0.92, relatedSkillId: "sk-hr-helpdesk", relatedUseCaseId: "uc-hr-helpdesk", system: "ServiceNow", region: "Global" },
    privacy: standardSignalPrivacy,
    riskLevel: "medium",
    createdAt: "2026-05-28T07:45:00.000Z",
  },
  {
    id: "ws-hr-positive-feedback",
    source: "harness",
    eventType: "feedback_given",
    department: "HR",
    process: "Employee policy self-service",
    summary: "Post-run feedback is trending positive for cited HR policy answers, with escalation requests concentrated in leave determinations.",
    metadata: { count: 164, confidence: 0.88, sentiment: "positive", relatedSkillId: "sk-hr-helpdesk", relatedUseCaseId: "uc-hr-helpdesk" },
    privacy: standardSignalPrivacy,
    riskLevel: "low",
    createdAt: "2026-05-28T07:52:00.000Z",
  },
  {
    id: "ws-finance-approval-delay",
    source: "finance_system",
    eventType: "approval_waiting",
    department: "Finance",
    process: "Invoice exception handling",
    teamId: "ap-exceptions",
    summary: "Non-PO exception packets spend most elapsed time waiting for approver clarification on missing PO context.",
    metadata: { volume: 980, cycleTimeHours: 46, delayHours: 21, confidence: 0.9, relatedSkillId: "sk-invoice-triage", relatedUseCaseId: "uc-invoice-triage", system: "SAP" },
    privacy: { ...standardSignalPrivacy, consentBasis: "business_record" },
    riskLevel: "medium",
    createdAt: "2026-05-28T07:30:00.000Z",
  },
  {
    id: "ws-finance-rework",
    source: "workflow",
    eventType: "rework_detected",
    department: "Finance",
    process: "Invoice exception handling",
    summary: "Workflow metadata shows repeated rework when invoice, PO, and receipt records disagree.",
    metadata: { count: 212, cycleTimeHours: 38, delayHours: 16, confidence: 0.86, relatedSkillId: "sk-invoice-triage", relatedUseCaseId: "uc-invoice-triage" },
    privacy: { ...standardSignalPrivacy, consentBasis: "system_metadata" },
    riskLevel: "medium",
    createdAt: "2026-05-28T06:58:00.000Z",
  },
  {
    id: "ws-legal-context-gap",
    source: "legal_system",
    eventType: "context_gap",
    department: "Legal",
    process: "Contract first-pass review",
    teamId: "legal-ops",
    summary: "Clause playbook lookups lack complete fallback language for mutual indemnity and data processing addenda.",
    metadata: { count: 47, confidence: 0.82, relatedSkillId: "sk-contract-review", relatedUseCaseId: "uc-contract-review", relatedContextSource: "Contract Repository", system: "iManage" },
    privacy: { ...standardSignalPrivacy, consentBasis: "business_record", retentionDays: 60 },
    riskLevel: "high",
    createdAt: "2026-05-27T19:22:00.000Z",
  },
  {
    id: "ws-legal-blocker",
    source: "harness",
    eventType: "governance_blocker",
    department: "Legal",
    process: "Contract first-pass review",
    summary: "Governance review is blocked until DocuSign send remains hard-disabled and grounding eval failures are remediated.",
    metadata: { count: 1, confidence: 0.94, relatedSkillId: "sk-contract-review", relatedUseCaseId: "uc-contract-review" },
    privacy: standardSignalPrivacy,
    riskLevel: "high",
    createdAt: "2026-05-27T18:50:00.000Z",
  },
  {
    id: "ws-procurement-intake-variant",
    source: "procurement_system",
    eventType: "process_variant",
    department: "Procurement",
    process: "Purchase request intake",
    teamId: "global-procurement",
    summary: "Requesters use seven different intake paths for similar software purchases, causing category and vendor rework.",
    metadata: { volume: 540, cycleTimeHours: 72, delayHours: 18, confidence: 0.84, relatedUseCaseId: "uc-po-assist", system: "Coupa" },
    privacy: { ...standardSignalPrivacy, consentBasis: "system_metadata" },
    riskLevel: "medium",
    createdAt: "2026-05-27T17:15:00.000Z",
  },
  {
    id: "ws-it-routing",
    source: "service_now",
    eventType: "handoff_delayed",
    department: "IT",
    process: "Incident routing",
    teamId: "it-service-desk",
    summary: "Incident reassignment chains are concentrated in VPN, access, and device provisioning categories.",
    metadata: { volume: 4100, cycleTimeHours: 9, delayHours: 4, confidence: 0.93, relatedSkillId: "sk-it-incident", relatedUseCaseId: "uc-it-incident", system: "ServiceNow" },
    privacy: { ...standardSignalPrivacy, consentBasis: "system_metadata" },
    riskLevel: "medium",
    createdAt: "2026-05-28T06:40:00.000Z",
  },
  {
    id: "ws-it-skill-used",
    source: "harness",
    eventType: "skill_used",
    department: "IT",
    process: "Incident routing",
    summary: "IT Incident Auto-Triage usage is increasing after production promotion, with strong completion rates.",
    metadata: { volume: 920, confidence: 0.91, sentiment: "positive", relatedSkillId: "sk-it-incident", relatedUseCaseId: "uc-it-incident" },
    privacy: standardSignalPrivacy,
    riskLevel: "low",
    createdAt: "2026-05-28T08:10:00.000Z",
  },
  {
    id: "ws-compliance-stale-source",
    source: "sharepoint",
    eventType: "context_gap",
    department: "Compliance",
    process: "Regulatory change monitoring",
    teamId: "grc",
    summary: "Regulatory Library freshness evidence is stale and blocks confidence in automated obligation summaries.",
    metadata: { count: 12, cycleTimeHours: 120, delayHours: 48, confidence: 0.87, relatedUseCaseId: "uc-compliance-monitor", relatedContextSource: "Regulatory Library", system: "GRC Repository" },
    privacy: { ...standardSignalPrivacy, consentBasis: "business_record", retentionDays: 120 },
    riskLevel: "restricted",
    createdAt: "2026-05-28T06:00:00.000Z",
  },
  {
    id: "ws-ops-kb-questions",
    source: "teams",
    eventType: "question_asked",
    department: "Operations",
    process: "Frontline knowledge support",
    teamId: "ops-enablement",
    summary: "Aggregated channel topics show repeated questions about product exceptions, escalation criteria, and refund workflows.",
    metadata: { volume: 2300, cycleTimeHours: 5, delayHours: 2, confidence: 0.8, relatedSkillId: "sk-ops-kb", relatedUseCaseId: "uc-ops-kb", relatedContextSource: "Product Knowledge Base" },
    privacy: { ...standardSignalPrivacy, consentBasis: "aggregated" },
    riskLevel: "low",
    createdAt: "2026-05-28T08:05:00.000Z",
  },
  {
    id: "ws-ops-training",
    source: "learning_platform",
    eventType: "training_completed",
    department: "Operations",
    process: "Frontline knowledge support",
    summary: "Operations champion cohort completed Skill usage training and is ready to support pilot expansion.",
    metadata: { volume: 68, confidence: 0.95, sentiment: "positive", relatedSkillId: "sk-ops-kb", relatedUseCaseId: "uc-ops-kb" },
    privacy: { ...standardSignalPrivacy, consentBasis: "explicit_opt_in", retentionDays: 365 },
    riskLevel: "low",
    createdAt: "2026-05-27T20:15:00.000Z",
  },
];

export const demoReport = `# Northwind Group — AI Enablement Executive Brief

## Portfolio at a glance
- 7 use cases across HR, Finance, Legal, Procurement, IT, Compliance, and Operations
- 5 governed Skills live (2 in production, 2 in pilot, 1 in review)
- Estimated annualized value delivered to date: $998K

## Highlights this period
- **IT Incident Auto-Triage v3.1.0** promoted to production after a 94% eval pass with zero critical failures.
- **HR Policy Helpdesk** scaled enterprise-wide, deflecting ~70% of tier-1 tickets.
- **Invoice Exception Triage** approved with conditions; mandatory human approval enforced for non-PO spend.

## Attention required
- **Contract First-Pass Review** is in governance review with a grounding eval at 84% (below the 90% threshold) and 2 critical failures.
- **Regulatory Library** context index is stale (10 days); refresh before advancing the Regulatory Change Monitor.

## Next 30 days
1. Remediate Contract Review grounding failures and re-run the eval suite.
2. Launch the Procurement Intake Assistant pilot (approved for pilot).
3. Refresh the Regulatory Library index and submit the Compliance use case to governance.`;

export const demoOrganization: OrganizationSettings = {
  id: "demo",
  name: "Northwind Group",
  slug: "northwind",
  workspaceLabel: "AI Enablement OS",
  primaryColor: "#3b5bdb",
  updatedAt: "2026-05-28T08:00:00.000Z",
};

function demoWorkflowNode(params: {
  id: string;
  blockType: string;
  title: string;
  subtitle: string;
  description: string;
  tone: "green" | "blue" | "purple" | "amber" | "red" | "slate";
  x: number;
  y: number;
  systemPrompt?: string;
  toolId?: string;
  requiresApproval?: boolean;
  approvalRole?: string;
  outputSchema?: string;
}) {
  const colors: Record<typeof params.tone, string> = {
    green: "#16a34a",
    blue: "#2563eb",
    purple: "#7c3aed",
    amber: "#d97706",
    red: "#dc2626",
    slate: "#64748b",
  };

  return {
    id: params.id,
    position: { x: params.x, y: params.y },
    data: {
      label: `${params.title}\n${params.subtitle}`,
      blockType: params.blockType,
      title: params.title,
      subtitle: params.subtitle,
      description: params.description,
      tone: params.tone,
      provider: "local",
      model: "local-enterprise-reasoner",
      temperature: 0.2,
      maxTokens: 4096,
      systemPrompt: params.systemPrompt ?? "",
      toolId: params.toolId ?? "",
      requiresApproval: params.requiresApproval ?? false,
      approvalRole: params.approvalRole ?? "ai_enablement_director",
      timeoutSeconds: 120,
      retryCount: 1,
      outputSchema: params.outputSchema ?? "",
    },
    style: {
      border: `1.5px solid ${colors[params.tone]}`,
      color: "#0f172a",
      background: "#ffffff",
      borderRadius: 8,
      boxShadow: "0 1px 2px rgba(15,23,42,0.06)",
      fontSize: 12,
      fontWeight: 650,
      lineHeight: 1.35,
      padding: "10px 12px",
      whiteSpace: "pre-line",
      width: 156,
    },
  };
}

function demoWorkflowEdge(source: string, target: string, label?: string) {
  return {
    id: `edge-${source}-${target}`,
    source,
    target,
    label,
    markerEnd: { type: "arrowclosed" },
  };
}

export const demoWorkflowNodes = [
  demoWorkflowNode({
    id: "demo-wf-start",
    blockType: "manual_trigger",
    title: "Start",
    subtitle: "Finance close request",
    description: "Starts from an approved finance close summary request.",
    tone: "green",
    x: 80,
    y: 180,
  }),
  demoWorkflowNode({
    id: "demo-wf-retrieve",
    blockType: "retrieve_documents",
    title: "Retrieve Docs",
    subtitle: "Finance SOP + close folder",
    description: "Retrieves approved close calendar, variance notes, and SOP context with permission filtering.",
    tone: "blue",
    x: 300,
    y: 180,
  }),
  demoWorkflowNode({
    id: "demo-wf-extract",
    blockType: "extract_data",
    title: "Extract Data",
    subtitle: "Invoices, variances, owners",
    description: "Extracts variance owner, amount, source, blocker, and confidence fields.",
    tone: "purple",
    x: 520,
    y: 180,
    systemPrompt: "Extract structured variance fields from approved close artifacts. Preserve source references and flag missing or ambiguous values.",
    outputSchema: "CloseVarianceExtraction",
  }),
  demoWorkflowNode({
    id: "demo-wf-analyze",
    blockType: "llm_analysis",
    title: "Analyze Variance",
    subtitle: "Risk and narrative",
    description: "Drafts source-grounded close narrative, unresolved blockers, and confidence score.",
    tone: "purple",
    x: 740,
    y: 180,
    systemPrompt: "Analyze close variance evidence using approved context only. Separate source facts from interpretation and flag uncertainty, missing documentation, and high-risk discrepancies.",
    outputSchema: "CloseAnalysisOutput",
  }),
  demoWorkflowNode({
    id: "demo-wf-condition",
    blockType: "condition",
    title: "Risk Check",
    subtitle: "High risk?",
    description: "Branches to human review when a variance is high risk, low confidence, or missing source evidence.",
    tone: "amber",
    x: 740,
    y: 360,
  }),
  demoWorkflowNode({
    id: "demo-wf-approval",
    blockType: "human_approval",
    title: "Human Review",
    subtitle: "Finance manager",
    description: "Pauses for finance manager approval before action or externalized summary.",
    tone: "red",
    x: 960,
    y: 360,
    requiresApproval: true,
    approvalRole: "ai_enablement_director",
  }),
  demoWorkflowNode({
    id: "demo-wf-summary",
    blockType: "llm_analysis",
    title: "Generate Summary",
    subtitle: "Close status brief",
    description: "Creates the final close summary and owner follow-up list.",
    tone: "amber",
    x: 520,
    y: 540,
    systemPrompt: "Generate a concise finance close summary with cited blockers, owners, next steps, and risk flags. Do not approve accounting entries or fabricate numbers.",
    outputSchema: "CloseSummary",
  }),
  demoWorkflowNode({
    id: "demo-wf-notify",
    blockType: "tool_call",
    title: "Create Tasks",
    subtitle: "Jira follow-ups",
    description: "Creates bounded owner follow-up tasks through the MCP Broker after policy checks.",
    tone: "blue",
    x: 740,
    y: 540,
    toolId: "t-jira-update",
    requiresApproval: false,
  }),
  demoWorkflowNode({
    id: "demo-wf-end",
    blockType: "end",
    title: "End",
    subtitle: "Evidence logged",
    description: "Completes the workflow and writes trace, eval, and evidence records.",
    tone: "green",
    x: 960,
    y: 540,
    outputSchema: "WorkflowResult",
  }),
];

export const demoWorkflowEdges = [
  demoWorkflowEdge("demo-wf-start", "demo-wf-retrieve"),
  demoWorkflowEdge("demo-wf-retrieve", "demo-wf-extract"),
  demoWorkflowEdge("demo-wf-extract", "demo-wf-analyze"),
  demoWorkflowEdge("demo-wf-analyze", "demo-wf-condition"),
  demoWorkflowEdge("demo-wf-condition", "demo-wf-approval", "Yes"),
  demoWorkflowEdge("demo-wf-condition", "demo-wf-summary", "No"),
  demoWorkflowEdge("demo-wf-approval", "demo-wf-notify"),
  demoWorkflowEdge("demo-wf-summary", "demo-wf-notify"),
  demoWorkflowEdge("demo-wf-notify", "demo-wf-end"),
];

export function buildDemoWorkspace(organizationId = "demo"): EnterpriseWorkspace {
  const now = "2026-05-28T08:00:00.000Z";
  return {
    schema: "enterprise-ai-enablement-os.workspace.v1",
    organizationId,
    workspaceMode: "demo",
    organization: { ...demoOrganization, id: organizationId },
    users: demoUsers,
    tools: demoTools,
    contextSources: demoContextSources,
    useCases: demoUseCases,
    skills: demoSkills,
    runs: demoRuns,
    toolRequests: demoToolRequests,
    auditLogs: demoAuditLogs,
    governanceReviews: demoGovernanceReviews,
    evalResults: demoEvalResults,
    workSignals: demoWorkSignals,
    commandOrders: [],
    workflow: { status: "Published", nodes: demoWorkflowNodes, edges: demoWorkflowEdges },
    report: demoReport,
    createdAt: "2026-01-10T12:00:00.000Z",
    updatedAt: now,
  };
}
